# Generated by Django 4.0.5 on 2022-06-26 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import instagram_app.models
import tkinter.tix
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram_app', '0004_postfilecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=tkinter.tix.Tree, null=True, upload_to=instagram_app.models.user1_directory_path, verbose_name='Picture'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captions', models.TextField(max_length=1500, verbose_name='Caption')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('content', models.ManyToManyField(related_name='contents', to='instagram_app.postfilecontent')),
                ('tags', models.ManyToManyField(related_name='tags', to='instagram_app.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
