# Generated by Django 4.0.5 on 2022-06-27 13:13

from django.db import migrations, models
import instagram_app.models
import tkinter.tix


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_app', '0006_stream_notification_likes_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.ImageField(blank=tkinter.tix.Tree, null=True, upload_to=instagram_app.models.user_directory_path, verbose_name='PostPicture'),
        ),
        migrations.DeleteModel(
            name='PostFileContent',
        ),
    ]
