# Generated by Django 4.0.5 on 2022-06-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_app', '0007_remove_post_content_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(to='instagram_app.post'),
        ),
    ]
